openapi: 3.0.0
info:
  title: RAG Query API
  version: 1.0.0
paths:
  /query:
    post:
      summary: Query the RAG system (full book retrieval)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: User's question.
                  example: What is ROS 2?
                user_id:
                  type: string
                  description: Optional user ID for personalization/logging.
                  example: user123
                module_context:
                  type: string
                  description: Optional module ID for contextual retrieval.
                  example: module-1-introduction
              required:
                - query
      responses:
        '200':
          description: Query successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    example: ROS 2 is a flexible framework for writing robot software...
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        module_id:
                          type: string
                          example: module-1-introduction
                        section_id:
                          type: string
                          example: ros2-nodes
                        text_snippet:
                          type: string
                          example: "ROS 2 nodes are processes..."
        '400':
          description: Invalid request
        '500':
          description: Internal server error
